package com.example.kal.db.vacancy

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Vacancy(
    @SerialName("id") val id: Long = -1, // bigint, nullable because it's generated by the database
    @SerialName("job") val job: String = "", // text, nullable
    @SerialName("money")val money: Int = 0, // integer, nullable
    @SerialName("organization")val organization: String = "", // text, nullable
    @SerialName("duties")val duties: String = "", // text, nullable
    @SerialName("requirements")val requirements: String = "", // text, nullable
    @SerialName("conditions")val conditions: String = "", // text, nullable
    @SerialName("address")val address: String = "", // text, nullable
    @SerialName("created_at") val date: String = ""  // timestamp with time zone, default value is now()
)

fun Vacancy.toPost(): VacancyPost {
    return VacancyPost(
        job = job,
        money = money,
        organization = organization,
        duties = duties,
        requirements = requirements,
        conditions = conditions,
        address = address
    )
}
